import { Injectable } from "@angular/core";
import { BaseResource } from "../../base/base.resource";

@Injectable({
  providedIn: "root",
})
export class InformacionLogisticaDetalleResource extends BaseResource {
  override pantalla: any[] = [
    {
      countryCode: [
        "CO",
        "US",
        "DO",
        "EC",
        "GT",
        "HN",
        "HT",
        "MX",
        "NI",
        "PE",
        "SV",
        "VE",
        "VG",
      ],
      screens: {
        scr_title: "Detalle Información Logística",
        scr_button_save_title: "¿Desea agregar este registro?",
        scr_button_cancel_label: "¿Quiere cancelar?",
        scr_button_cancel_ok_text: "Sí",
        scr_button_cancel_text: "No",
        scr_button_cancel_title: "Cancelar",
        scr_button_delete_label: "¿Realmente desea eliminar el registro?",
        scr_button_delete_ok_text: "Sí",
        scr_button_delete_text: "No",
        scr_search_button: "Buscar",
        scr_dropdown_menu_columns: [{ placeholder: "Seleccione" }],
        scr_messages: [
          { message: "Archivo descargado!" },
          { message: "No hay datos con el filtro seleccionado" },
          { message: "Excel" },
          { message: "Generando Archivo..." },
          { message: "El registro fue actualizado correctamente" },
          { message: "El registro fue insertado correctamente" },
          {
            message:
              "Ocurrió un error insertando masivamente, se generó un archivo Excel con los errores de validación.",
          },
          { message: "El archivo fue procesado correctamente" },
          { message: "Cliente encontrado correctamente" },
          { message: "Error Insertando Información Logística" },
        ],
        scr_modals: [
          { viewName: "v_clientes_informacion_logistica", title: "Cliente"},
          { viewName: "v_subzonas", title: "Subzona" },
          { viewName: "v_colonias", title: "Colonia" },
          { viewName: "v_rutas", title: "Ruta" },
          { viewName: "v_tipos_negocio", title: "T. Negocio" },
          { viewName: "v_areas", title: "Área" },
          { viewName: "v_rvent", title: "Ventana Horaria" },
        ],
        scr_labels: [
          { label_name: "Cliente" },
          { label_name: "Nombre Cliente" },
          { label_name: "Cobrar A" },
          { label_name: "Nombre" },
          { label_name: "Canal" },
          { label_name: "Dirección Cliente" },
          { label_name: "Dir. Centro Acopio" },
          { label_name: "Dirección Correo" },
          { label_name: "Teléfono" },
          { label_name: "Fax" },
          { label_name: "Id" },
          { label_name: "País" },
          { label_name: "Departamento" },
          { label_name: "Cód. Postal" },
          { label_name: "Ciudad" },
          { label_name: "Municipio" },
          { label_name: "Descripción Municipio" },
          { label_name: "Barrio" },
          { label_name: "Subzona" },
          { label_name: "Descripción Sub zona" },
          { label_name: "Hora Recibo" },
          { label_name: "Área" },
          { label_name: "Transbordo" },
          { label_name: "Característica" },
          { label_name: "Colonia" },
          { label_name: "Descripción Colonia" },
          { label_name: "Estrato" },
          { label_name: "T. Negocio" },
          { label_name: "Descripción T. Negocio" },
          { label_name: "Estado" },
          { label_name: "Ruta Entrega" },
          { label_name: "Descripción Ruta Entrega" },
          { label_name: "Secuencia de Entrega" },
          { label_name: "Ruta Visita" },
          { label_name: "Descripción Ruta Visita" },
          { label_name: "Secuencia Visita" },
          { label_name: "Restricción de Recibo" },
          { label_name: "Tipo Vehículo Máximo" },
          { label_name: "Desc. Tipo Vehículo Máximo" },
          { label_name: "Horarios de cargue" },
          { label_name: "Área Nielsen" },
          { label_name: "UM Maniobra Descargue" },
          { label_name: "Tarifa Maniobra Descargue" },
          { label_name: "Observaciones" },
          { label_name: "Ventana Horaria" },
          { label_name: "Ventana Horaria Descripción" },
          { label_name: "Ingreso Información Logística" },
          { label_name: "Desea guardar la Información Logística para el cliente {0}?" },
          { label_name: "Aceptar" },
          { label_name: "Cancelar" },
        ],
      },
    },
  ];
}
