import { Injectable } from "@angular/core";
import { BaseResource } from "../base/base.resource";

@Injectable({
  providedIn: "root",
})
export class IngresoInformacionLogisticaResource extends BaseResource {
  override pantalla: any[] = [
    {
      countryCode: [
        "CO",
        "US",
        "DO",
        "EC",
        "GT",
        "HN",
        "HT",
        "MX",
        "NI",
        "PE",
        "SV",
        "VE",
        "VG",
      ],
      screens: {
        scr_title: "Ingreso Información Logística",
        scr_fileName_export: "Ingreso Información Logística export",
        scr_fileName_template: "Ingreso Información Logística template",
        scr_fileName_errors: "Ingreso Información Logística errors",
        scr_listName: "grupo_separacion",
        scr_label_column_error: "Resultado de validación",
        scr_button_save_title: "¿Desea agregar este registro?",
        scr_button_cancel_label: "¿Quiere cancelar?",
        scr_button_cancel_ok_text: "Si",
        scr_button_cancel_text: "No",
        scr_button_cancel_title: "Cancelar",
        scr_button_delete_label: "¿Realmente desea eliminar el registro?",
        scr_button_delete_ok_text: "Si",
        scr_button_delete_text: "No",
        scr_search_button: "Buscar",
        scr_clear_button: "Limpiar",
        scr_actions_label: "Acciones",
        src_max_len: 8,
        scr_dropdown_menu_columns: [{ placeholder: "Seleccione" }],
        scr_modal_detalle_title: "Ingreso Información Logística",
        scr_modals: [
          { viewName: 'v_clientes_informacion_logistica', title: 'Canales Preventa' },
        ],
        scr_labels: [
          { label_name: "Cliente" },
          { label_name: "Nombre Cliente" },
          { label_name: "Cobrar A" },
          { label_name: "Nombre" },
          { label_name: "Canal" },
          { label_name: "Dirección Cliente" },
          { label_name: "Dir. Centro Acopio" },
          { label_name: "Dirección Correo" },
          { label_name: "Teléfono" },
          { label_name: "Fax" },
          { label_name: "Id" },
          { label_name: "País" },
          { label_name: "Departamento" },
          { label_name: "Cód. Postal" },
          { label_name: "Ciudad" },
          { label_name: "Municipio" },
          { label_name: "Descripción Municipio" },
          { label_name: "Barrio" },
          { label_name: "Subzona" },
          { label_name: "Descripción Sub zona" },
          { label_name: "Hora Recibo" },
          { label_name: "Área" },
          { label_name: "Transbordo" },
          { label_name: "Característica" },
          { label_name: "Colonia" },
          { label_name: "Descripción Colonia" },
          { label_name: "Estrato" },
          { label_name: "T. Negocio" },
          { label_name: "Descripción T. Negocio" },
          { label_name: "Estado" },
          { label_name: "Ruta Entrega" },
          { label_name: "Descripción Ruta Entrega" },
          { label_name: "Secuencia de Entrega" },
          { label_name: "Ruta Visita" },
          { label_name: "Descripción Ruta Visita" },
          { label_name: "Secuencia Visita" },
          { label_name: "Restricción de Recibo" },
          { label_name: "Tipo Vehículo Máximo" },
          { label_name: "Desc. Tipo Vehículo Máximo" },
          { label_name: "Horarios de cargue" },
          { label_name: "Área Nielsen" },
          { label_name: "UM Maniobra Descargue" },
          { label_name: "Tarifa Maniobra Descargue" },
          { label_name: "Observaciones" },
          { label_name: "Ventana Horaria" },
          { label_name: "Ventana Horaria Descripción" },
          { label_name: "Ingreso Información Logística" },
          { label_name: "Desea guardar la Información Logística para el cliente {0}?" },
          { label_name: "Aceptar" },
          { label_name: "Cancelar" },
        ],
        scr_messages: [
          { message: "Archivo descargado!" },
          { message: "No hay datos con el filtro seleccionado" },
          { message: "Plantilla" },
          { message: "Generando Archivo..." },
          { message: "El registro fue actualizado correctamente" },
          { message: "El registro fue insertado correctamente" },
          {
            message:
              "Ocurrió un error insertando masivamente, se generó un archivo Excel con los errores de validación.",
          },
          { message: "El archivo fue procesado correctamente" },
        ],
        scr_table_columns: [
          {
            col_name: "Cliente",
            col_ref: "Entidad.cli_codigo",
            is_filter_parameter: true,
            is_visible: false,
            is_visible_column: true,
            is_mandatory: true,
            is_mandatory_message: "Debe ingresar Cliente",
            col_width: "120px",
            boolean_label_affirmative: null,
            boolean_label_negative: null,
          },
          {
            col_name: "Cobrar a",
            col_ref: "Entidad.cli_bill",
            is_filter_parameter: false,
            is_visible: false,
            is_visible_column: true,
            is_mandatory: true,
            is_mandatory_message: "Debe ingresar Cliente",
            col_width: "120px",
            boolean_label_affirmative: null,
            boolean_label_negative: null,
          },
          {
            col_name: "Nombre",
            col_ref: "Entidad.cli_cob_nombre",
            is_filter_parameter: false,
            is_visible: false,
            is_visible_column: true,
            is_mandatory: true,
            is_mandatory_message: "Debe ingresar Cliente",
            col_width: "180px",
            boolean_label_affirmative: null,
            boolean_label_negative: null,
          },
          {
            col_name: "Colonia",
            col_ref: "Entidad.rc_secuencia",
            is_filter_parameter: true,
            is_visible: false,
            is_visible_column: true,
            is_mandatory: false,
            is_mandatory_message: null,
            col_width: "120px",
            boolean_label_affirmative: null,
            boolean_label_negative: null,
          },
          {
            col_name: "Descripción Colonia",
            col_ref: "Entidad.col_descripcion",
            is_filter_parameter: false,
            is_visible: false,
            is_visible_column: true,
            is_mandatory: false,
            is_mandatory_message: null,
            col_width: "160px",
            boolean_label_affirmative: null,
            boolean_label_negative: null,
          },
          {
            col_name: "Subzona",
            col_ref: "Entidad.sub_codigo",
            is_filter_parameter: true,
            is_visible: false,
            is_visible_column: true,
            is_mandatory: false,
            is_mandatory_message: null,
            col_width: "120px",
            boolean_label_affirmative: null,
            boolean_label_negative: null,
          },
          {
            col_name: "Desc. Subzona",
            col_ref: "Entidad.rs_descripcion_subzona",
            is_filter_parameter: false,
            is_visible: false,
            is_visible_column: true,
            is_mandatory: false,
            is_mandatory_message: null,
            col_width: "120px",
            boolean_label_affirmative: null,
            boolean_label_negative: null,
          },
          {
            col_name: "T. Negocio",
            col_ref: "Entidad.tneg_codigo",
            is_filter_parameter: true,
            is_visible: false,
            is_visible_column: true,
            is_mandatory: true,
            is_mandatory_message: null,
            col_width: "140px",
            boolean_label_affirmative: null,
            boolean_label_negative: null,
          },
          {
            col_name: "Desc. T. Negocio",
            col_ref: "Entidad.tne_descripcion",
            is_filter_parameter: false,
            is_visible: false,
            is_visible_column: true,
            is_mandatory: false,
            is_mandatory_message: null,
            col_width: "140px",
            boolean_label_affirmative: null,
            boolean_label_negative: null,
          },
          {
            col_name: "Ruta Entrega",
            col_ref: "Entidad.rut_codigo_entrega",
            is_filter_parameter: true,
            is_visible: false,
            is_visible_column: true,
            is_mandatory: false,
            is_mandatory_message: null,
            col_width: "150px",
            boolean_label_affirmative: null,
            boolean_label_negative: null,
          },
          {
            col_name: "Ruta Visita",
            col_ref: "Entidad.rut_codigo_visita",
            is_filter_parameter: true,
            is_visible: false,
            is_visible_column: true,
            is_mandatory: false,
            is_mandatory_message: null,
            col_width: "150px",
            boolean_label_affirmative: null,
            boolean_label_negative: null,
          },
          {
            col_name: "Área",
            col_ref: "Entidad.cli_area",
            is_filter_parameter: true,
            is_visible: false,
            is_visible_column: true,
            is_mandatory: false,
            is_mandatory_message: null,
            col_width: "100px",
            boolean_label_affirmative: null,
            boolean_label_negative: null,
          },
          {
            col_name: "Característica",
            col_ref: "Entidad.cli_contado",
            is_filter_parameter: true,
            is_visible: false,
            is_visible_column: true,
            is_mandatory: false,
            is_mandatory_message: null,
            col_width: "160px",
            boolean_label_affirmative: null,
            boolean_label_negative: null,
          },
          {
            col_name: "Secuencia Entrega",
            col_ref: "Entidad.cli_secuencia_entrega",
            is_filter_parameter: false,
            is_visible: false,
            is_visible_column: true,
            is_mandatory: false,
            is_mandatory_message: null,
            col_width: "150px",
            boolean_label_affirmative: null,
            boolean_label_negative: null,
          },
          {
            col_name: "Secuencia Visita",
            col_ref: "Entidad.cli_secuencia_visita",
            is_filter_parameter: false,
            is_visible: false,
            is_visible_column: true,
            is_mandatory: false,
            is_mandatory_message: null,
            col_width: "150px",
            boolean_label_affirmative: null,
            boolean_label_negative: null,
          },
          {
            col_name: "Estrato",
            col_ref: "Entidad.cli_estrato",
            is_filter_parameter: false,
            is_visible: false,
            is_visible_column: true,
            is_mandatory: false,
            is_mandatory_message: null,
            col_width: "100px",
            boolean_label_affirmative: null,
            boolean_label_negative: null,
          },
          {
            col_name: "Estado",
            col_ref: "Entidad.cli_estado",
            is_filter_parameter: false,
            is_visible: false,
            is_visible_column: true,
            is_mandatory: false,
            is_mandatory_message: null,
            col_width: "100px",
            boolean_label_affirmative: "Activo",
            boolean_label_negative: "Inactivo",
          },
          {
            col_name: "Hora Recibo",
            col_ref: "Entidad.cli_hora_recibido",
            is_filter_parameter: false,
            is_visible: false,
            is_visible_column: true,
            is_mandatory: false,
            is_mandatory_message: null,
            col_width: "120px",
            boolean_label_affirmative: null,
            boolean_label_negative: null,
            func_to_execute: "segundosAHora",
          },
          {
            col_name: "Transbordo",
            col_ref: "Entidad.cli_transbordo",
            is_filter_parameter: false,
            is_visible: false,
            is_visible_column: true,
            is_mandatory: false,
            is_mandatory_message: null,
            col_width: "120px",
            boolean_label_affirmative: "Sí",
            boolean_label_negative: "No",
          },
          {
            col_name: "Ventana Horaria",
            col_ref: "Entidad.rvent_codigo",
            is_filter_parameter: false,
            is_visible: false,
            is_visible_column: true,
            is_mandatory: false,
            is_mandatory_message: null,
            col_width: "250px",
            boolean_label_affirmative: null,
            boolean_label_negative: null,
          },
        ]
      },
    },
  ];

}
